frontend:
  replicaCount: 2
  image:
    repository: <aws-account-id>.dkr.ecr.<region>.amazonaws.com/frontend-service
    tag: "latest"
  service:
    type: LoadBalancer
    port: 80

backend:
  replicaCount: 1
  image:
    repository: <aws-account-id>.dkr.ecr.<region>.amazonaws.com/backend-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 3000
